# Production environment configurations
server:
  port: 2412

spring:
  jpa:
    open-in-view: false
    show-sql: false # Disable SQL logging in production
    hibernate:
      ddl-auto: update # Validate schema in production
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://160.25.72.91:3306/fill_form}
    username: ${DATABASE_USERNAME:fillform}
    password: ${DATABASE_PASSWORD:admin@}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 8
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      pool-name: FillFormHikariPool
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:khaosat.dev@gmail.com}
    password: ${MAIL_PASSWORD:iyqmpuqjfdqlztos}
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true

# Production settings

# Production logging configuration
logging:
  level:
    com.dienform: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# Security Configuration
security:
  sensitive-files:
    enabled: true
    log-blocked-requests: true
    return-404-for-blocked: true

  rate-limiting:
    enabled: true
    max-requests-per-minute: 500
    max-requests-per-hour: 1000

# Google Form optimization settings for production
google:
  api:
    key: ${GOOGLE_API_KEY:AIzaSyBCFk8JZ8OYLVEjs92cSLfcccyFH7VyeU0}
  form:
    # Performance settings optimized for production
    timeout-seconds: 60
    thread-pool-size: 3
    max-retries: 2
    retry-delay-ms: 2000

    # Feature flags for production
    auto-submit: true
    headless: true # Enable headless mode in production
    async-enabled: true
    cache-enabled: true

    # Advanced settings
    similarity-threshold: 0.8 # Higher threshold for production
  # Google OAuth Configuration
  oauth:
    client-id: 576659994866-msfjs05kr5mqtk8nsli7hmmrid9qlc3t.apps.googleusercontent.com

# Queue Management Configuration for production
queue:
  max-size: 200
  check-interval: 15000 # 15 seconds for faster processing
  max-retries: 5
  retry-delay: 10000 # 10 seconds

# Realtime Socket settings
realtime:
  socket:
    port: 9092
    path: /socket.io
    progress-emit-interval-ms: ${FILLREQ_PROGRESS_EMIT_INTERVAL_MS:1000}
    progress-emit-delta: ${FILLREQ_PROGRESS_EMIT_DELTA:1}
    burst-max-per-sec: ${FILLREQ_BURST_MAX_EVENTS_PER_SEC:10}

campaign:
  scheduler:
    fixed-rate: 30000 # Check every 60 seconds in production
    enabled: true

# JWT Configuration for production
jwt:
  secret: ${JWT_SECRET:YourSuperSecretJWTKeyThatShouldBeAtLeast256BitsLongForHS256AlgorithmSecurity}
  access-expiration: ${JWT_ACCESS_EXPIRATION_MS:86400000} # 1 day
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_SEC:2592000} # 7 days

app:
  frontend:
    url: ${FRONTEND_URL:https://160.25.72.91:3000}
  security:
    enable-ip-on-register: ${ENABLE_IP_ON_REGISTER:false}
  cookie:
    domain: ${APP_COOKIE_DOMAIN:true}
    secure: ${APP_COOKIE_SECURE:true}
    samesite: ${APP_COOKIE_SAMESITE:Strict}
  monitoring:
    enabled: true
  async:
    core-pool-size: 2 # Optimized for 2-core server
    max-pool-size: 4 # Optimized for 2-core server
    queue-capacity: 50 # Reduced queue capacity
    thread-name-prefix: Async-

facebook:
  app:
    id: ${FACEBOOK_APP_ID:}
    secret: ${FACEBOOK_APP_SECRET:}

ai:
  suggestion:
    enabled: true
    provider: gemini
    queue:
      max-size: 100
      max-concurrent: 2
      processing-interval: 5000
      max-retries: 3
      retry-delay: 10000
    gemini:
      api-key: AIzaSyDINl0xLfEZm5_QVT_nang30Vgt8El7VZU
      base-url: https://generativelanguage.googleapis.com/v1beta/models
      model: gemini-2.0-flash
      max-tokens: 800000
      timeout: 30000
      batch-size: 8
      parallelism: 2
    validation:
      max-sample-count: 1000
      max-questions-per-form: 1000
      min-sample-count: 1
      max-instruction-length: 1000
