server:
  port: 2412

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/fill_form
    username: fillform
    password: admin@
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: khaosat.dev@gmail.com
    password: iyqmpuqjfdqlztos
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true

# Local logging configuration
logging:
  level:
    com.dienform: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Google Form optimization settings
google:
  api:
    key: AIzaSyBCFk8JZ8OYLVEjs92cSLfcccyFH7VyeU0
  form:
    # Performance settings
    timeout-seconds: 30
    thread-pool-size: 5
    max-retries: 3
    retry-delay-ms: 1000

    # Feature flags
    auto-submit: true # Set to false for local debugging
    headless: true # Set to false for local debugging
    async-enabled: true
    cache-enabled: true

    # Advanced settings
    similarity-threshold: 0.7
  # Google OAuth Configuration
  oauth:
    client-id: 576659994866-msfjs05kr5mqtk8nsli7hmmrid9qlc3t.apps.googleusercontent.com

# Campaign Scheduler Configuration
campaign:
  scheduler:
    fixed-rate: 10000 # Check every 10 seconds (10000ms)
    enabled: true

# JWT Configuration for production
jwt:
  secret: ${JWT_SECRET:YourSuperSecretJWTKeyThatShouldBeAtLeast256BitsLongForHS256AlgorithmSecurity}
  access-expiration: ${JWT_ACCESS_EXPIRATION_MS:86400000} # 1 day
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_SEC:2592000} # 7 days

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
realtime:
  socket:
    path: /socket.io
    progress-emit-interval-ms: ${FILLREQ_PROGRESS_EMIT_INTERVAL_MS:1000}
    progress-emit-delta: ${FILLREQ_PROGRESS_EMIT_DELTA:1}
    burst-max-per-sec: ${FILLREQ_BURST_MAX_EVENTS_PER_SEC:10}
    port: 9092
  security:
    enable-ip-on-register: ${ENABLE_IP_ON_REGISTER:false}
  cookie:
    domain: ${APP_COOKIE_DOMAIN:}
    secure: ${APP_COOKIE_SECURE:false}
    samesite: ${APP_COOKIE_SAMESITE:Lax}

facebook:
  app:
    id: ${FACEBOOK_APP_ID:}
    secret: ${FACEBOOK_APP_SECRET:}
