server:
  port: 2412

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/fill_form?lock_wait_timeout=60&innodb_lock_wait_timeout=60&innodb_deadlock_detect=ON
    username: fillform
    password: admin@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      pool-name: FillFormHikariPool
  mail:
    host: smtp.gmail.com
    port: 587
    username: khaosat.dev@gmail.com
    password: iyqmpuqjfdqlztos
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true

# Local logging configuration
logging:
  level:
    com.dienform: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Google Form optimization settings
google:
  api:
    key: AIzaSyBCFk8JZ8OYLVEjs92cSLfcccyFH7VyeU0
  form:
    # Performance settings optimized for 2-core server
    timeout-seconds: 45 # Reduced from 60s
    thread-pool-size: 2 # Optimized for 2-core server
    max-retries: 2 # Reduced from 3
    retry-delay-ms: 2000 # Increased from 1000ms

    # Feature flags
    auto-submit: true # Set to false for local debugging
    headless: false # Set to false for local debugging
    async-enabled: true
    cache-enabled: true

    # Advanced settings
    similarity-threshold: 0.7
  # Google OAuth Configuration
  oauth:
    client-id: 576659994866-msfjs05kr5mqtk8nsli7hmmrid9qlc3t.apps.googleusercontent.com

# Queue Management Configuration
queue:
  max-size: 10 # Reduced from 20
  check-interval: 30000 # 45 seconds - increased for 2-core
  max-retries: 2 # Reduced from 3
  retry-delay: 8000 # 8 seconds - increased

# Campaign Scheduler Configuration
campaign:
  scheduler:
    fixed-rate: 120000 # Check every 2 minutes (120000ms) - reduced for 2-core
    enabled: true

# JWT Configuration for production
jwt:
  secret: ${JWT_SECRET:YourSuperSecretJWTKeyThatShouldBeAtLeast256BitsLongForHS256AlgorithmSecurity}
  access-expiration: ${JWT_ACCESS_EXPIRATION_MS:86400000} # 1 day
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_SEC:2592000} # 7 days

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  monitoring:
    enabled: true
  async:
    core-pool-size: 2 # Optimized for 2-core server
    max-pool-size: 4 # Optimized for 2-core server
    queue-capacity: 50 # Reduced queue capacity
    thread-name-prefix: Async-

realtime:
  socket:
    path: /socket.io
    progress-emit-interval-ms: ${FILLREQ_PROGRESS_EMIT_INTERVAL_MS:1000}
    progress-emit-delta: ${FILLREQ_PROGRESS_EMIT_DELTA:1}
    burst-max-per-sec: ${FILLREQ_BURST_MAX_EVENTS_PER_SEC:10}
    port: 9092
  security:
    enable-ip-on-register: ${ENABLE_IP_ON_REGISTER:false}
  cookie:
    domain: ${APP_COOKIE_DOMAIN:}
    secure: ${APP_COOKIE_SECURE:false}
    samesite: ${APP_COOKIE_SAMESITE:Lax}

facebook:
  app:
    id: ${FACEBOOK_APP_ID:}
    secret: ${FACEBOOK_APP_SECRET:}

ai:
  suggestion:
    enabled: true
    provider: gemini
    queue:
      max-size: 50
      max-concurrent: 2
      processing-interval: 5000
      max-retries: 3
      retry-delay: 10000
    gemini:
      api-key: AIzaSyDINl0xLfEZm5_QVT_nang30Vgt8El7VZU
      base-url: https://generativelanguage.googleapis.com/v1beta/models
      model: gemini-2.0-flash
      max-tokens: 800000
      timeout: 30000
      batch-size: 10
      parallelism: 3
    validation:
      max-sample-count: 1000
      max-questions-per-form: 1000
      min-sample-count: 1
      max-instruction-length: 1000
