# Production environment configurations
server:
  port: 2412

spring:
  jpa:
    open-in-view: false
    show-sql: false # Disable SQL logging in production
    hibernate:
      ddl-auto: update # Validate schema in production
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://160.25.72.91:3306/fill_form}
    username: ${DATABASE_USERNAME:fillform}
    password: ${DATABASE_PASSWORD:admin@}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:khaosat.dev@gmail.com}
    password: ${MAIL_PASSWORD:iyqmpuqjfdqlztos}
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true

# Production settings

# Production logging configuration
logging:
  level:
    com.dienform: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# Google Form optimization settings for production
google:
  api:
    key: ${GOOGLE_API_KEY:AIzaSyBCFk8JZ8OYLVEjs92cSLfcccyFH7VyeU0}
  form:
    # Performance settings optimized for production
    timeout-seconds: 60
    thread-pool-size: 10
    max-retries: 5
    retry-delay-ms: 2000

    # Feature flags for production
    auto-submit: true
    headless: true # Enable headless mode in production
    async-enabled: true
    cache-enabled: true

    # Advanced settings
    similarity-threshold: 0.8 # Higher threshold for production
  # Google OAuth Configuration
  oauth:
    client-id: 576659994866-msfjs05kr5mqtk8nsli7hmmrid9qlc3t.apps.googleusercontent.com

# Campaign Scheduler Configuration for production
campaign:
  scheduler:
    fixed-rate: 30000 # Check every 30 seconds in production
    enabled: true

# JWT Configuration for production
jwt:
  secret: ${JWT_SECRET:YourSuperSecretJWTKeyThatShouldBeAtLeast256BitsLongForHS256AlgorithmSecurity}
  access-expiration: ${JWT_ACCESS_EXPIRATION_MS:86400000} # 1 day
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_SEC:2592000} # 7 days

app:
  frontend:
    url: ${FRONTEND_URL:http://160.25.72.91:3000}
  security:
    enable-ip-on-register: ${ENABLE_IP_ON_REGISTER:false}
  cookie:
    domain: ${APP_COOKIE_DOMAIN:}
    secure: ${APP_COOKIE_SECURE:false}
    samesite: ${APP_COOKIE_SAMESITE:Lax}

facebook:
  app:
    id: ${FACEBOOK_APP_ID:}
    secret: ${FACEBOOK_APP_SECRET:}
