# Production environment configurations
server:
  port: 2412

spring:
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
  jpa:
    open-in-view: false
    show-sql: false # Disable SQL logging in production
    hibernate:
      ddl-auto: none # Validate schema in production
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
        connection:
          timezone: Asia/Ho_Chi_Minh
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://192.168.2.24:3306/fill_form?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh}
    username: ${DATABASE_USERNAME:fillform}
    password: ${DATABASE_PASSWORD:admin@}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: "SET SESSION time_zone = '+07:00'"
      maximum-pool-size: 40
      minimum-idle: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      pool-name: FillFormHikariPool
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:khaosat.dev@gmail.com}
    password: ${MAIL_PASSWORD:iyqmpuqjfdqlztos}
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true

# Production settings

# Production logging configuration
logging:
  level:
    com.dienform: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# Security Configuration
security:
  sensitive-files:
    enabled: true
    log-blocked-requests: true
    return-404-for-blocked: true

  rate-limiting:
    enabled: true
    max-requests-per-minute: 2000
    max-requests-per-hour: 5000

# Google Form optimization settings for production
google:
  api:
    key: ${GOOGLE_API_KEY:AIzaSyBCFk8JZ8OYLVEjs92cSLfcccyFH7VyeU0}
  form:
    # Performance settings optimized for 8-core production server
    timeout-seconds: 60 # Increased for production stability
    thread-pool-size: 16 # Optimized for 8 cores (2 human + 6 fast)
    max-retries: 3 # Increased for better reliability
    retry-delay-ms: 1500 # Optimized for faster retry
    per-request:
      max-inflight: 2

    # Feature flags for production
    auto-submit: true
    headless: true # Enable headless mode in production
    async-enabled: true
    cache-enabled: true
    submit-when-visible: true
    # Disable branch probing/backtracking when reading multi-section forms
    branch-capture:
      enabled: false

    # Adaptive timeout settings
    adaptive-timeout:
      base-form-timeout: 180 # 5 phút cho mỗi form
      max-form-timeout: 1800 # 30 phút tối đa cho mỗi form
      queue-wait-multiplier: 60 # 1 phút/queue position

    # Circuit breaker settings
    circuit-breaker:
      max-failures: 3 # Skip form sau 3 lần fail
      timeout-seconds: 60 # Reset circuit breaker sau 1 phút
      skip-failed-forms: true # Bỏ qua form lỗi

    # Legacy timeout settings (for backward compatibility)
    fast-timeout-seconds: 600 # 10 phút cho fast mode
    human-timeout-seconds: 600 # 10 phút cho human-like
    heavy-load-threshold: 50 # Increased threshold for 8-core server
    heavy-timeout-multiplier: 2.0 # Increased multiplier for better performance

    # Advanced settings
    similarity-threshold: 0.7

    # Batch processing settings
    batch-size: 50 # Increased for 8-core server
    enable-batch-processing: true

    # Adaptive thread pool settings
    pool:
      rebalance-ms: 3000 # More frequent rebalancing for better performance
      human:
        min: 1 # Minimum 1 human thread
      fast:
        min: 1 # Minimum 3 fast threads for parallel processing
  # Google OAuth Configuration
  oauth:
    client-id: 576659994866-msfjs05kr5mqtk8nsli7hmmrid9qlc3t.apps.googleusercontent.com

# Queue Management Configuration for production
queue:
  max-size: 200 # Increased for 8-core server
  check-interval: 10000 # 10 seconds for faster processing
  max-retries: 5
  retry-delay: 8000 # 8 seconds for faster retry

# Realtime Socket settings
realtime:
  socket:
    port: 9092
    path: /socket.io
    progress-emit-interval-ms: ${FILLREQ_PROGRESS_EMIT_INTERVAL_MS:1000}
    progress-emit-delta: ${FILLREQ_PROGRESS_EMIT_DELTA:1}
    burst-max-per-sec: ${FILLREQ_BURST_MAX_EVENTS_PER_SEC:10}

campaign:
  scheduler:
    fixed-rate: 20000 # Check every 20 seconds for faster processing
    enabled: true

# JWT Configuration for production
jwt:
  secret: ${JWT_SECRET:YourSuperSecretJWTKeyThatShouldBeAtLeast256BitsLongForHS256AlgorithmSecurity}
  access-expiration: ${JWT_ACCESS_EXPIRATION_MS:86400000} # 1 day
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_SEC:2592000} # 7 days

app:
  frontend:
    url: ${FRONTEND_URL:https://192.168.2.24:3000}
  security:
    enable-ip-on-register: ${ENABLE_IP_ON_REGISTER:false}
  cookie:
    domain: ${APP_COOKIE_DOMAIN:}
    secure: ${APP_COOKIE_SECURE:true}
    samesite: ${APP_COOKIE_SAMESITE:Strict}
  monitoring:
    enabled: true
  async:
    core-pool-size: 8 # Optimized for 8-core server
    max-pool-size: 22 # Optimized for 8-core server
    queue-capacity: 200 # Increased queue capacity
    thread-name-prefix: Async-
  business:
    async:
      core-pool-size: 3 # Business operations (form parsing, encoding)
      max-pool-size: 6 # Separate from Selenium pools
      queue-capacity: 100 # Business task queue
      thread-name-prefix: BizAsync-
  request-limiter:
    max-concurrent: 8 # Increased for 8-core server

facebook:
  app:
    id: ${FACEBOOK_APP_ID:}
    secret: ${FACEBOOK_APP_SECRET:}

ai:
  suggestion:
    enabled: true
    provider: gemini
    queue:
      max-size: 200
      max-concurrent: 8
      processing-interval: 3000
      max-retries: 3
      retry-delay: 8000
    gemini:
      api-key: AIzaSyDINl0xLfEZm5_QVT_nang30Vgt8El7VZU
      base-url: https://generativelanguage.googleapis.com/v1beta/models
      model: gemini-2.0-flash
      max-tokens: 800000
      timeout: 30000
      batch-size: 3
      parallelism: 4
    validation:
      max-sample-count: 1000
      max-questions-per-form: 1000
      min-sample-count: 1
      max-instruction-length: 1000

# SEPAY Payment Configuration
sepay:
  secret-key: ${SEPAY_SECRET_KEY:msfjs05kr5mqtk8nsli7hmmrid9qlc3t}
  qr-base-url: ${SEPAY_QR_BASE_URL:https://qr.sepay.vn/img}
  api-url: ${SEPAY_API_URL:https://api.sepay.vn}
  webhook-url: ${SEPAY_WEBHOOK_URL:https://192.168.2.24:2412/api/payments/sepay/webhook}
  order-expiration-minutes: 15
  webhook-retry-minutes: 5
  max-retry-attempts: 3
