server:
  port: 2412

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/fill_form
    username: fillform
    password: admin@
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: khaosat.dev@gmail.com
    password: iyqmpuqjfdqlztos
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# Local development settings
app:
  frontend:
    url: http://localhost:3000

# Local logging configuration
logging:
  level:
    com.dienform: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Google Form optimization settings
google:
  api:
    key: AIzaSyBCFk8JZ8OYLVEjs92cSLfcccyFH7VyeU0
  form:
    # Performance settings
    timeout-seconds: 30
    thread-pool-size: 5
    max-retries: 3
    retry-delay-ms: 1000

    # Feature flags
    auto-submit: false # Set to false for local debugging
    headless: false # Set to false for local debugging
    async-enabled: true
    cache-enabled: true

    # Debug settings
    debug-mode: true # Enable debug mode for local development
    keep-browser-open: true # Keep browser open for debugging

    # Advanced settings
    similarity-threshold: 0.7
  # Google OAuth Configuration
  oauth:
    client-id: 174305364945-1p8i19sc1gclleccatiirch72r5gdt0b.apps.googleusercontent.com

# Campaign Scheduler Configuration
campaign:
  scheduler:
    fixed-rate: 10000 # Check every 10 seconds (10000ms)
    enabled: true

# JWT Configuration
jwt:
  secret: YourSuperSecretJWTKeyThatShouldBeAtLeast256BitsLongForHS256AlgorithmSecurity
  expiration: 86400000 # 1 day
  refresh-expiration: 604800000 # 7 days
